/**
 * Building stats, footprints, production options and prerequisites.
 * Production options live here only, so no record duplicates who builds what.
 */
import type { BuildingTypeId } from '../core/ids';
import type { BuildingConfig } from './types';

export const BUILDING_CONFIG: Readonly<Record<BuildingTypeId, BuildingConfig>> = {
  hq: {
    id: 'hq',
    name: 'HQ',
    buildable: false,
    cost: 0,
    buildTimeSeconds: 0,
    maxHealth: 1500,
    footprint: { width: 4, height: 4 },
    visionRangeTiles: 7,
    produces: ['worker'],
    requires: [],
    requiresPower: false,
    acceptsDeliveries: true,
    armor: 'structure',
  },
  barracks: {
    id: 'barracks',
    name: 'Barracks',
    buildable: true,
    cost: 300,
    buildTimeSeconds: 12,
    maxHealth: 700,
    footprint: { width: 3, height: 3 },
    visionRangeTiles: 5,
    produces: ['infantry', 'fpvOperators'],
    requires: ['hq'],
    requiresPower: false,
    acceptsDeliveries: false,
    armor: 'structure',
  },
  factory: {
    id: 'factory',
    name: 'Factory',
    buildable: true,
    cost: 700,
    buildTimeSeconds: 22,
    maxHealth: 900,
    footprint: { width: 4, height: 4 },
    visionRangeTiles: 5,
    produces: ['tank', 'rocket'],
    requires: ['barracks', 'powerPlant'],
    requiresPower: true,
    acceptsDeliveries: false,
    armor: 'structure',
  },
  powerPlant: {
    id: 'powerPlant',
    name: 'Power Plant',
    buildable: true,
    cost: 250,
    buildTimeSeconds: 10,
    maxHealth: 500,
    footprint: { width: 3, height: 3 },
    visionRangeTiles: 4,
    produces: [],
    requires: ['hq'],
    requiresPower: false,
    acceptsDeliveries: false,
    armor: 'structure',
  },
  resourceDepot: {
    id: 'resourceDepot',
    name: 'Resource Depot',
    buildable: true,
    cost: 400,
    buildTimeSeconds: 15,
    maxHealth: 600,
    footprint: { width: 3, height: 3 },
    visionRangeTiles: 5,
    produces: [],
    requires: ['hq'],
    requiresPower: false,
    acceptsDeliveries: true,
    armor: 'structure',
  },
  unmannedSystemsCenter: {
    id: 'unmannedSystemsCenter',
    name: 'Unmanned Systems Forces Center',
    buildable: true,
    cost: 650,
    buildTimeSeconds: 20,
    maxHealth: 750,
    footprint: { width: 3, height: 3 },
    visionRangeTiles: 6,
    produces: [],
    requires: ['barracks', 'factory'],
    requiresPower: true,
    acceptsDeliveries: false,
    armor: 'structure',
  },
};
